ESimSolManufacturing/ESimSolFinancial/Controllers/BusinessUnitController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using ESimSol.BusinessObjects;
using System.Web.Script.Serialization;
using ESimSol.Reports;
using System.IO;
using System.Xml.Serialization;
using ESimSol.BusinessObjects.ReportingObject;
using System.Drawing;
using System.Drawing.Imaging;
using ICS.Core.Utility;
using System.Web;

namespace ESimSolFinancial.Controllers
{
    public class BusinessUnitController : Controller
    {
        #region Declaration
        BusinessUnit _oBusinessUnit = new BusinessUnit();
        List<BusinessUnit> _oBusinessUnits = new List<BusinessUnit>();

        TLocation _oTLocation = new TLocation();
        List<TLocation> _oTLocations = new List<TLocation>();
        List<Location> _oLocations = new List<Location>();
        string _sErrorMessage = "";
        string _sSQL = "";
        #endregion
        #region Functions
        private void MakeSQL(string Arguments)
        {
            _sSQL = "";
            _sSQL = "SELECT * FROM View_BusinessUnit";
            string sCode = (Arguments.Split(';')[1].Split('~')[0] == null) ? "" : Arguments.Split(';')[1].Split('~')[0];
            string sName = (Arguments.Split(';')[1].Split('~')[1] == null) ? "" : Arguments.Split(';')[1].Split('~')[1];
            //string sBusinessUnitIDs = _bForPrint ? (Arguments.Split(';')[1].Split('~')[1] == null) ? "" : Arguments.Split(';')[1].Split('~')[1] : "";
            string sSQL = "";

            #region Code
            if (sCode != null)
            {
                if (sCode != "")
                {
                    Global.TagSQL(ref sSQL);
                    sSQL = sSQL + " Code LIKE '%" + sCode + "%' ";
                }
            }
            #endregion
            #region Name
            if (sName != null)
            {
                if (sName != "")
                {
                    Global.TagSQL(ref sSQL);
                    sSQL = sSQL + " Name LIKE '%" + sName + "%' ";
                }
            }
            #endregion
           
            if (sSQL != "")
            { _sSQL = _sSQL + sSQL; }
           
        }
        #endregion

        #region Used Code
        public ActionResult ViewBusinessUnits(int menuid)
        {
            this.Session.Remove(SessionInfo.MenuID);
            this.Session.Add(SessionInfo.MenuID, menuid);
            this.Session.Add(SessionInfo.AuthorizationRolesMapping, AuthorizationRoleMapping.GetsByModuleAndUser(((int)EnumModuleName.BusinessUnit).ToString(), (int)Session[SessionInfo.currentUserID], ((User)Session[SessionInfo.CurrentUser]).UserID));
            _oBusinessUnits = new List<BusinessUnit>();
            _oBusinessUnits = BusinessUnit.Gets(((User)Session[SessionInfo.CurrentUser]).UserID);

            return View(_oBusinessUnits);
        }
        
        public ActionResult ViewBusinessUnit(int id)
        {
            _oBusinessUnit = new BusinessUnit();
            if (id > 0)
            {
                _oBusinessUnit = _oBusinessUnit.Get(id, ((User)Session[SessionInfo.CurrentUser]).UserID);
            }
            _oBusinessUnit.BusinessNatures = EnumObject.jGets(typeof(EnumBusinessNature));
            _oBusinessUnit.LegalFormats = EnumObject.jGets(typeof(EnumLegalFormat));
            _oBusinessUnit.BusinessUnitTypeObjs = EnumObject.jGets(typeof(EnumBusinessUnitType));

            ClientOperationSetting oTempClientOperationSetting = new ClientOperationSetting();
            oTempClientOperationSetting = oTempClientOperationSetting.GetByOperationType((int)EnumOperationType.BanglaFont, ((User)Session[SessionInfo.CurrentUser]).UserID);
            ViewBag.COS = oTempClientOperationSetting;

            return View(_oBusinessUnit);
        }
        [HttpPost]
        public JsonResult Gets(BusinessUnit oBusinessUnit)
        {
            List<BusinessUnit> oBusinessUnits = new List<BusinessUnit>();
            oBusinessUnit.ErrorMessage = oBusinessUnit.ErrorMessage == null ? "" : oBusinessUnit.ErrorMessage;
            this.MakeSQL(oBusinessUnit.ErrorMessage);

            oBusinessUnits = BusinessUnit.Gets(_sSQL, ((User)Session[SessionInfo.CurrentUser]).UserID);

            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string sjson = serializer.Serialize((object)oBusinessUnits);
            return Json(sjson, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Get(BusinessUnit oBusinessUnit)
        {
            _oBusinessUnit = new BusinessUnit();
            try
            {
                if (oBusinessUnit.BusinessUnitID > 0)
                {
                    _oBusinessUnit = _oBusinessUnit.Get(oBusinessUnit.BusinessUnitID, ((User)Session[SessionInfo.CurrentUser]).UserID);
                }
            }
            catch (Exception ex)
            {
                _oBusinessUnit = new BusinessUnit();
                _oBusinessUnit.ErrorMessage = ex.Message;
            }
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string sjson = serializer.Serialize(_oBusinessUnit);
            return Json(sjson, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewUploadLogo(int id)
        {
            _oBusinessUnit = new BusinessUnit();
            if (id > 0)
            {
                _oBusinessUnit = _oBusinessUnit.GetWithImage(id, ((User)Session[SessionInfo.CurrentUser]).UserID);
            }
            _oBusinessUnit.BusinessNatures = EnumObject.jGets(typeof(EnumBusinessNature));
            _oBusinessUnit.LegalFormats = EnumObject.jGets(typeof(EnumLegalFormat));
            _oBusinessUnit.BusinessUnitTypeObjs = EnumObject.jGets(typeof(EnumBusinessUnitType));

            if (_oBusinessUnit.BUImage != null)
            {
                _oBusinessUnit.BUImageSt = "data:image/Jpeg;base64," + Convert.ToBase64String(_oBusinessUnit.BUImage);
            }
            return View(_oBusinessUnit);
        }

        [HttpPost]
        public JsonResult UploadLogo(double ts)
        {
            byte[] aImageInByteArray;
            _oBusinessUnit = new BusinessUnit();
            string sResult = "";
            try
            {
                _oBusinessUnit.BusinessUnitID = Convert.ToInt32(Request.Headers["BusinessUnitID"]);
                #region File
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files[0];
                    int fileSize = file.ContentLength;
                    //fileName = file.FileName;
                    string mimeType = file.ContentType;
                    if (file != null && file.ContentLength > 0)
                    {
                        Image oImage = Image.FromStream(file.InputStream, true, true);
                        aImageInByteArray = null;
                        using (MemoryStream ms = new MemoryStream())
                        {
                            oImage.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                            aImageInByteArray = ms.ToArray();
                        }
                        _oBusinessUnit.BUImage = aImageInByteArray;
                    }
                    else
                    {
                        _oBusinessUnit.BUImage = null;
                    }
                }
                else
                {
                    _oBusinessUnit.BUImage = null;
                }

                #endregion

                _oBusinessUnit = _oBusinessUnit.UpdateImage((int)Session[SessionInfo.currentUserID]);
                sResult = "Data Save Successfully";
            }
            catch (Exception ex)
            {
                _oBusinessUnit = new BusinessUnit();
                _oBusinessUnit.ErrorMessage = ex.Message;
            }

            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string sjson = serializer.Serialize(sResult);
            return Json(sjson, JsonRequestBehavior.AllowGet);
        }

        public Image GetBULogo(BusinessUnit oBusinessUnit)
        {
            if (oBusinessUnit.BUImage != null)
            {
                string fileDirectory = Server.MapPath("~/Content/CompanyLogo.jpg");
                if (System.IO.File.Exists(fileDirectory))
                {
                    System.IO.File.Delete(fileDirectory);
                }

                MemoryStream m = new MemoryStream(oBusinessUnit.BUImage);
                System.Drawing.Image img = System.Drawing.Image.FromStream(m);
                img.Save(fileDirectory, ImageFormat.Jpeg);
                return img;
            }
            else
            {
                return null;
            }
        }


        #endregion

        public ActionResult ViewBusinessUnitPicker(string sName, double nts)
        {
            _oBusinessUnits = new List<BusinessUnit>();
            _oBusinessUnit = new BusinessUnit();
            string sSql = "";
            try
            {
                if (string.IsNullOrEmpty(sName))
                {
                    sSql = "SELECT * FROM View_BusinessUnit order by Name ";
                }
                else
                {
                    sSql = "SELECT * FROM View_BusinessUnit WHERE Name LIKE '%" + sName + "%'";
                }
                _oBusinessUnits = BusinessUnit.Gets(sSql, ((User)Session[SessionInfo.CurrentUser]).UserID);
                if (_oBusinessUnits.Count <= 0)
                {
                    throw new Exception("Data Not Found !");
                }
            }
            catch (Exception ex)
            {
                _oBusinessUnits = new List<BusinessUnit>();
                _oBusinessUnit.ErrorMessage = ex.Message;
                _oBusinessUnits.Add(_oBusinessUnit);
            }
            return PartialView(_oBusinessUnits);
        }

        [HttpPost]
        public JsonResult Save(BusinessUnit oBusinessUnit)
        {

ESimSolManufacturing/ESimSolFinancial/Views/BusinessUnit/ViewBusinessLocationAssign.cshtml
<html>

@{
    ViewBag.Title = "Business Location Assign";  
}
@model ESimSol.BusinessObjects.BusinessUnit         
<body>
       
            <div id="divLocationTree" class="easyui-panel" title="Assign Operation Unit" style="font-family:Tahoma; height:100%; width:100%">
                <div class="easyui-panel"  style="width:100%;height:88%;overflow:auto">
                    <ul id="ttBLocation" data-options="checkbox:true"></ul>
                </div>


                <div style="width:100%; height:10%">
                    <fieldset>
                        <legend style="font-weight: bold">Action : </legend>
                        <table border="0" cellspacing="2" cellpadding="2" style="font-size: 11px; font-weight: bold; width:100%">
                            <tr>
                                <td style="width:80%; text-align:right"></td>
                                <td style="width: 10%">
                                    <a id="btnOk" href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-ok" plain="false">Commit</a>
                                </td>
                                <td style="width: 10%">
                                    <a id="btnClose" href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-cancel" plain="false">Close</a>
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                </div>
            </div>
</body>
</html>

<script type="text/javascript">
    var _oBusinessUnit=null;
    var _oSelectedMenuKeys=null;
    var _oTLocation=null;
    var _sBaseAddress='';
    var _nMenuid=0;
    $(document).ready(function () {
        //debugger;
        _sBaseAddress =@Html.Raw( new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(HttpContext.Current.Session[SessionInfo.BaseAddress]));
        _nMenuid = @Html.Raw(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(HttpContext.Current.Session[SessionInfo.MenuID]));
        _oBusinessUnit =@Html.Raw( new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Model));
        LoadBusinessLocation();

        _sBusinessUnitHeader=sessionStorage.getItem("BusinessUnitHeader");
        _sBusinessUnitHeader="Assign Operation Unit for->"+_sBusinessUnitHeader
        $('#divLocationTree').panel({ title:_sBusinessUnitHeader});
    });



    function LoadBusinessLocation()
    {
        
        _oTLocation =_oBusinessUnit.TLocation;
        if (_oTLocation != null) {
            $('#ttBLocation').tree({
                data: [_oTLocation]
            });
            RefreshControl();
        }
    }



    //Checked Selected Items
    function RefreshControl()
    {

        var oAllNodes=$('#ttBLocation').tree('getChecked', 'unchecked');
        if(oAllNodes!=null)
        {
            for(var n=0;n<oAllNodes.length;n++)
            {
                if(oAllNodes[n].IsChecked)
                {
                    if($('#ttBLocation').tree('isLeaf', oAllNodes[n].target))
                    {
                      $('#ttBLocation').tree('check', oAllNodes[n].target);
                    }
                }
            }
        }
    }





    $("#btnOk").click(function () {
        debugger;
        if(_oBusinessUnit==null)
        {
            alert("Invalid BusinessUnit please try again!");
            return;
        }

        if(_oBusinessUnit.BusinessUnitID<=0)
        {
            alert("Invalid Business Unit please try again!");
            return;
        }


        var _oSelectedLocations= [];
        _oSelectedLocations= $('#ttBLocation').tree('getChecked', ['checked','indeterminate']);
        if(_oSelectedLocations==null || _oSelectedLocations.length<=0)
        {
            alert("Please select at least one item!");
            return;
        }

        var oBusinessLocations=[];
        //get indeterminate items
        //_oSelectedLocations= [];
        //_oSelectedLocations= $('#ttBLocation').tree('getChecked', 'indeterminate');
        for(var i=0; i<_oSelectedLocations.length;i++)
        {
            var oBusinessLocationTemp= {
                BusinessLocationID:_oSelectedLocations[i].BLID,
                BusinessUnitID:_oBusinessUnit.BusinessUnitID,
                LocationID : _oSelectedLocations[i].id
            }
            oBusinessLocations.push(oBusinessLocationTemp);
        }

        var oBusinessLocation= {
            BusinessUnitID:_oBusinessUnit.BusinessUnitID,
            BusinessLocations:oBusinessLocations
        }

        $.ajax({
            type: "POST",
            dataType: "json",
            url: '@Url.Action("SaveBL", "BusinessUnit")',
            traditional: true,
            data:  JSON.stringify(oBusinessLocation),
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                //debugger;
                var oBusinessLocation = jQuery.parseJSON(data);
                if (oBusinessLocation.ErrorMessage=="" ||oBusinessLocation.ErrorMessage==null)
                {
                    alert("Data Save Succesfully!!");

                    window.location.href = _sBaseAddress+ "/BusinessUnit/ViewBusinessUnits?menuid="+_nMenuid;

                }
                else{
                    alert(oBusinessLocation.ErrorMessage);
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        });

    })

    $("#btnClose").click(function(){
        window.location.href = _sBaseAddress+ "/BusinessUnit/ViewBusinessUnits?menuid="+_nMenuid;
    });

    $(document).keydown(function(e) {
        if(e.which == 27)//escape=27
        {
            window.location.href = _sBaseAddress+ "/BusinessUnit/ViewBusinessUnits?menuid="+_nMenuid;
        }
    });
</script>

ESimSolManufacturing/ESimSolFinancial/Views/BusinessUnit/ViewBusinessLocations.cshtml
@model IEnumerable<ESimSol.BusinessObjects.TBusinessLocation>
@{
    ViewBag.Title = "Business Location List";
}


<div style="margin-left: 0px; height: 100%; width:100%">
    <table id="tblBusinessLocation" title="BusinessLocation List" class="easyui-treegrid" fit="true" fitcolumns="true" data-options="idField:'id',treeField:'text', rownumbers:'true', toolbar:'#toolbar'">
        <thead>
            <tr>
                <th field="text" style="width:100%;">Name</th>
                
            </tr>
        </thead>
    </table>
    <div id="toolbar">
        @*<input type="text" id="txtSearchByCode" placeholder="Search by Code" style="width:120px" onclick="Clearfield()" />
    <input type="text" id="txtSearchByName" placeholder="Search by name" style="width:150px" onclick="ClearNamefield()" />
    <a id="btnAdd" href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-add" plain="true" onclick="Add()">Add</a>
    <a id="btnEdit" href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-edit" plain="true" onclick="Edit()">Edit</a>
    <a id="btnDelete" href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-remove" plain="true" onclick="Delete()">Delete</a>*@
        
        
    </div>
</div>





<script type="text/javascript">
    var _oTBusinessLocation=null;
    var _oTBusinessLocations=null;
    var _oTChildrenBusinessLocations=null;
    var nID =null;
    var _sBaseAddress="";
    $(document).ready(function () {
        // 
        debugger;
        _oTBusinessLocation=@Html.Raw( new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Model));

        _oTBusinessLocations =sessionStorage.getItem("BusinessLocations");
        _oTChildrenBusinessLocations =sessionStorage.getItem("ChildrenBusinessLocations");
        _nID =parseInt(sessionStorage.getItem("SelectedRowIndex"));
        _oTChildrenBusinessLocations=_oTChildrenBusinessLocations!=null?jQuery.parseJSON(_oTChildrenBusinessLocations):[];
        _oTBusinessLocations=_oTBusinessLocations!=null?jQuery.parseJSON(_oTBusinessLocations):[];

        if(_oTBusinessLocations!=null && _oTBusinessLocations.length>0)
        {
            
            if(_nID>0 && _oTChildrenBusinessLocations!=null && _oTChildrenBusinessLocations.length>0)
            {
                _oTBusinessLocations=  ChildrenReset(_oTBusinessLocations);
                _oTBusinessLocation=_oTBusinessLocations;
            }
        }
        else
        {
            _oTBusinessLocations=_oTBusinessLocation;
        }
        RefreshList(_oTBusinessLocations);
        if(nID>0)
        {
            $('#tblBusinessLocation').treegrid('select', nID);
        }
        sessionStorage.setItem("ChildrenBusinessLocations",null);
    });

    function ChildrenReset(oChildren){
        debugger;
        for(var i=0;i<oChildren.length;i++){
            if(_nID===oChildren[i].id){
                oChildren[i].children=[];
                oChildren[i].children=_oTChildrenBusinessLocations;
                //break;
            }
            else{
                if(oChildren[i].children!=null){
                    ChildrenReset(oChildren[i].children);
                }
            }
        }
        return oChildren;
    }

    $('#txtSearchByCode').keypress(function (e) {
        // 
        var c = String.fromCharCode(e.which);
        var txtSearchByCode = document.getElementById('txtSearchByCode').value;
        txtSearchByCode = txtSearchByCode + c;

        var bFlag=false;
        var sAccountHeadCode="";
        var rows = $('#tblBusinessLocation').treegrid('getChildren',1);
        for(i=0;i<rows.length;++i){
            sAccountHeadCode=rows[i]['code'].substring(0, txtSearchByCode.length);
            if(txtSearchByCode.toUpperCase()==sAccountHeadCode.toUpperCase())
            {
                var id=rows[i]['id'];
                $('#tblBusinessLocation').treegrid('select',id);
                break;
            }
        }
    });

    $('#txtSearchByName').keypress(function (e) {
        // 
        var c = String.fromCharCode(e.which);
        var txtSearchByName = document.getElementById('txtSearchByName').value;
        txtSearchByName = txtSearchByName + c;

        var bFlag=false;
        var sAccountHeadName="";
        var rows = $('#tblBusinessLocation').treegrid('getChildren',1);
        for(i=0;i<rows.length;++i){
            sAccountHeadName=rows[i]['text'].substring(0, txtSearchByName.length);
            if(txtSearchByName.toUpperCase()==sAccountHeadName.toUpperCase())
            {
                var id=rows[i]['id'];
                $('#tblBusinessLocation').treegrid('select',id);
                break;
            }
        }
    });




    





    function Refresh()
    {
        // 
        $('#tblBusinessLocation').treegrid('reload');	// reload the all rows
    }





    function Edit()
    {
        debugger;
        var oBusinessLocation= $('#tblBusinessLocation').treegrid('getSelected'); 
        if(oBusinessLocation==null || oBusinessLocation.id<=0)
        {
            alert("Please select a item from list!");
            return;
        }

      
        
        var oBusinessLocations=$('#tblBusinessLocation').treegrid('getData');
        sessionStorage.setItem("BusinessLocations", JSON.stringify(oBusinessLocations));        
        sessionStorage.setItem("SelectedRowIndex", oBusinessLocation.id);   
        sessionStorage.setItem("BusinessLocationHeader", "Edit BusinessLocation");


       

        window.location.href = _sBaseAddress+ "/BusinessLocation/EditBusinessLocation?id="+oBusinessLocation.id;
    }


    $('#btnAdd').click( function ()
    {
        debugger;
        var oBusinessLocation= $('#tblBusinessLocation').treegrid('getSelected'); 
        if(oBusinessLocation==null || oBusinessLocation.id<=0)
        {
            alert("Please select an item from list!");
            return false;
        }
        if(oBusinessLocation.BusinessLocationType===3){
            alert('Cannot add Children to Site!');
            return false;
        }

      
        
        
        var oBusinessLocations=$('#tblBusinessLocation').treegrid('getData');
        var oTempChildren=$('#tblBusinessLocation').treegrid('getChildren',oBusinessLocation.id);
        var oChildren=[];
        if(oTempChildren!=null && oTempChildren.length>0){
            for(var i=0;i<oTempChildren.length;i++){
                if(oTempChildren[i].parentid===oBusinessLocation.id){
                    oChildren.push(oTempChildren[i]);
                }
            }
        }

        sessionStorage.setItem("BusinessLocations", JSON.stringify(oBusinessLocations));
        sessionStorage.setItem("ChildrenBusinessLocations", JSON.stringify(oChildren));
        sessionStorage.setItem("SelectedRowIndex", oBusinessLocation.id);   
        sessionStorage.setItem("BusinessLocationHeader", "Add BusinessLocation");
               
        window.location.href = _sBaseAddress+ "/BusinessLocation/ViewBusinessLocation?id="+oBusinessLocation.id;

        
    });


    function IsExists(nparentid, id)
    {
        var oChildNodes= $('#tblBusinessLocation').treegrid('getChildren',nparentid);
        for(var j=0;j<oChildNodes.length;j++)
        {
            if(oChildNodes[j].id==id)
            {
                return true;
            }
        }
        return false;
    }


    function ReloadChildData(nparentid)
    {
        $.ajax({
            type: "GET",
            dataType: "json",
            url : _sBaseAddress+  "/BusinessLocation/getchildren",
            traditional: true,
            data: {parentid:nparentid},
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                 
                var oTBusinessLocations= jQuery.parseJSON(data);
                if(oTBusinessLocations!=null)
                {
                    if (oTBusinessLocations.length>0) {
                        for(i=0; i<oTBusinessLocations.length; i++)
                        {
                            $('#tblBusinessLocation').treegrid('append',{ parent: nparentid, data: [oTBusinessLocations[i]] });
                        }
                        $('#tblBusinessLocation').treegrid('select',nparentid);
                        $('#tblBusinessLocation').treegrid('expand',nparentid);
                    }
                }
                else {
                    //alert('Data not found!!');
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }

        });
    }

    function RefreshList(oTBusinessLocation)
    {
        data= oTBusinessLocation;
        data={"total":""+data.length+"","rows":data};
        $('#tblBusinessLocation').treegrid('loadData',data);
    }

    function Delete()
    {
         
        var oBusinessLocation= $('#tblBusinessLocation').datagrid('getSelected');
        if(oBusinessLocation==null || oBusinessLocation.id<=0)
        {
            alert("Please select a item from list!");
            return;
        }
        if(oBusinessLocation.parentid==0 )
        {
            alert("Root BusinessLocation not deletable");
            return;
        }
        if (!confirm("Confirm to Delete?")) return ;
        var SelectedRowIndex=$('#tblBusinessLocation').datagrid('getRowIndex',oBusinessLocation);

        if (oBusinessLocation.id > 0)
        {
            $.ajax
            ({
                type: "POST",
                dataType: "json",
                url : _sBaseAddress+  "/BusinessLocation/Delete",
                data: JSON.stringify({ BusinessLocationID: oBusinessLocation.id }),
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    debugger;
                    feedbackmessage = jQuery.parseJSON(data);
                    if (feedbackmessage === "Deleted")
                    {
                        alert("Data Delete Successfully");
                        $('#tblBusinessLocation').treegrid('remove',oBusinessLocation.id);
                    }
                    else
                    {
                        alert(feedbackmessage);
                    }
                },
                error: function (xhr, status, error)
                {
                    alert(error);
                }

            });
        }
    }

    @*function Activity()
    {
        var oBusinessLocation = $('#tblBusinessLocation').datagrid('getSelected');
        if(oBusinessLocation==null || oBusinessLocation.id<=0)
        {
            alert("Invalid Field!!! please select a valid Field!");
            return false;
        }
        if (!confirm("Confirm to " + (oBusinessLocation.IsActive==true?" Inactive ?":" Active ?" ))) return ;
        var SelectedRowIndex=$('#tblBusinessLocation').datagrid('getRowIndex',oBusinessLocation);

        if (oBusinessLocation.id > 0)
        {
            debugger;

            $.ajax
               ({
                   type: "POST",
                   dataType: "json",
                   url: '@Url.Action("ActiveInactive", "BusinessLocation")',
                   data:  JSON.stringify(oBusinessLocation),
                   contentType: "application/json; charset=utf-8",
                   success: function (data)
                   {
                       var oBusinessLocation = jQuery.parseJSON(data);
                       $('#tblBusinessLocation').datagrid('updateRow',{index: SelectedRowIndex,	row: oBusinessLocation});
                       alert("Updated sucessfully");

                   },
                   error: function (xhr, status, error)
                   {
                       alert(error);
                   }
               });
        }
    }*@


</script>