ESimSolManufacturing/ESimSolFinancial/Controllers/KnitDyeingProgramAttachmentController.cs
using System;
using ICS.Core.Framework;
using ICS.Core.Utility;
using ICS.Core;
using ESimSol.BusinessObjects;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.IO;
using System.Drawing.Imaging;
using ESimSol.Reports;
using System.Drawing;
using System.Reflection;

namespace ESimSolFinancial.Controllers
{
    public class KnitDyeingProgramAttachmentController:Controller
    {
        #region  KnitDyeingProgramAttachment
        public ViewResult KnitDyeingProgramAttachments(int id, string ms, string OperationInfo)
        {
            KnitDyeingProgramAttachment oKnitDyeingProgramAttachment = new KnitDyeingProgramAttachment();
            List<KnitDyeingProgramAttachment> oKnitDyeingProgramAttachments = new List<KnitDyeingProgramAttachment>();
            oKnitDyeingProgramAttachments = KnitDyeingProgramAttachment.Gets(id, (int)Session[SessionInfo.currentUserID]);
            oKnitDyeingProgramAttachment.KnitDyeingProgramID = id;
            oKnitDyeingProgramAttachment.KnitDyeingProgramAttachments = oKnitDyeingProgramAttachments;
            TempData["message"] = ms;
            oKnitDyeingProgramAttachment.ErrorMessage = OperationInfo;
            return View(oKnitDyeingProgramAttachment);
        }

        [HttpPost]
        public ActionResult UploadAttchment(HttpPostedFileBase file, KnitDyeingProgramAttachment oKnitDyeingProgramAttachment)
        {
            string sErrorMessage = "", sRefNameOperationInfo = oKnitDyeingProgramAttachment.ErrorMessage;
            byte[] data;
            try
            {

                if (file != null && file.ContentLength > 0)
                {
                    using (Stream inputStream = file.InputStream)
                    {
                        MemoryStream memoryStream = inputStream as MemoryStream;
                        if (memoryStream == null)
                        {
                            memoryStream = new MemoryStream();
                            inputStream.CopyTo(memoryStream);
                        }
                        data = memoryStream.ToArray();
                    }

                    double nMaxLength = 1024 * 1024;
                    if (data == null || data.Length <= 0)
                    {
                        sErrorMessage = "Please select an file!";
                    }
                    else if (data.Length > nMaxLength)
                    {
                        sErrorMessage = "You can select maximum 1MB file size!";
                    }
                    else if (oKnitDyeingProgramAttachment.KnitDyeingProgramID <= 0)
                    {
                        sErrorMessage = "Your Selected Knit Dyeing Program Is Invalid!";
                    }
                    else
                    {
                        oKnitDyeingProgramAttachment.AttachFile = data;
                        oKnitDyeingProgramAttachment.FileName = file.FileName;
                        oKnitDyeingProgramAttachment.FileType = file.ContentType;
                        if(oKnitDyeingProgramAttachment.FileType.Substring(0,5)=="image")
                        {
                            oKnitDyeingProgramAttachment = oKnitDyeingProgramAttachment.Save((int)Session[SessionInfo.currentUserID]);
                        }
                        else
                        {
                            sErrorMessage = "Please Select Only Image";
                        }
                        
                    }
                }
                else
                {
                    sErrorMessage = "Please select an file!";
                }


            }
            catch (Exception ex)
            {
                sErrorMessage = "";
                sErrorMessage = ex.Message;
            }
            return RedirectToAction("KnitDyeingProgramAttachments", new { id = oKnitDyeingProgramAttachment.KnitDyeingProgramID, ms = sErrorMessage, OperationInfo = sRefNameOperationInfo });
        }


        public ActionResult DownloadAttachment(int id, double ts)
        {
            KnitDyeingProgramAttachment oKnitDyeingProgramAttachment = new KnitDyeingProgramAttachment();
            try
            {
                oKnitDyeingProgramAttachment.KnitDyeingProgramAttachmentID = id;
                oKnitDyeingProgramAttachment = KnitDyeingProgramAttachment.GetWithAttachFile(id, (int)Session[SessionInfo.currentUserID]);
                if (oKnitDyeingProgramAttachment.AttachFile != null)
                {
                    var file = File(oKnitDyeingProgramAttachment.AttachFile, oKnitDyeingProgramAttachment.FileType);
                    file.FileDownloadName = oKnitDyeingProgramAttachment.FileName;
                    TempData["message"] = "";
                    return file;
                }
                else
                {
                    return null;
                }
            }
            catch
            {
                throw new HttpException(404, "Couldn't find " + oKnitDyeingProgramAttachment.FileName);
            }
        }

        [HttpPost]
        public JsonResult DeleteAttachment(KnitDyeingProgramAttachment oKnitDyeingProgramAttachment)
        {
            string sErrorMease = "";
            try
            {
                sErrorMease = oKnitDyeingProgramAttachment.Delete(oKnitDyeingProgramAttachment.KnitDyeingProgramAttachmentID, (int)Session[SessionInfo.currentUserID]);
            }
            catch (Exception ex)
            {
                sErrorMease = ex.Message;
            }

            JavaScriptSerializer serializer = new JavaScriptSerializer();
            string sjson = serializer.Serialize(sErrorMease);
            return Json(sjson, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

ESimSolManufacturing/ESimSolFinancial/Views/KnitDyeingProgramAttachment/KnitDyeingProgramAttachments.cshtml
 <html>
@{
    ViewBag.Title = "KnitDyeing Program Attachment";
}
<body>

@model ESimSol.BusinessObjects.KnitDyeingProgramAttachment
<div style="font-family:Tahoma">           

@using (Html.BeginForm("UploadAttchment", "KnitDyeingProgramAttachment", FormMethod.Post, new { enctype = "multipart/form-data" }))
{   
    @Html.HiddenFor(model => model.KnitDyeingProgramID) 
    @Html.HiddenFor(model => model.ErrorMessage)
    <div style="margin-left:0px; margin-top:1px; height:490px" id="divatt">
        <table id="tblKnitDyeingProgramAttachment" title="KnitDyeingProgram Attachment List" class="easyui-datagrid" style="width:100%;height:490px" toolbar="#toolbar" fitcolumns="false" rownumbers="true" pagination="false" singleselect="true" autorowheight="false">
            <thead>
                <tr>
                    <th field="FileName" width="50%">Attatchment Name</th>
                    <th field="Remarks" width="30%">Remarks</th>
                    <th field="AttatchFileinString" width="18%" align="center" formatter="FormatDownload">Download</th>
                </tr>
            </thead>
        </table>​
        <div id="toolbar" style="font-family:Tahoma; margin-left:0px; height:28px; width:100%" >
            <table border="0"cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td style="width:30%"><input type="file" accept=".png, .jpg, .jpeg, .gif, .bmp" name="file" style="width:100%" /></td>
                    <td style="width:70%">
                        Remark : @Html.TextBoxFor(model => model.Remarks, new { style = "width: 25%;", id = "txtRemarks" })
                        <input id="btnSubmit" type="submit" value="Upload" style="width:75px; font-weight:bold" />
                        <input id="btnDelete" type="button" value="Delete" style="width:75px; font-weight:bold" />
                    </td>
                </tr>
            </table>
            
        </div>                                          
    </div>
    
}
    <fieldset>
        <legend style="font-weight:bold"> Action : </legend>
        <table border="0" cellspacing="2" cellpadding="2" style="font-size:12px; font-weight:bold" width="100%">
            <tr>
                <td style="width:52%; text-align:left;color:red;">             
                    <label id="lblError"> @TempData["message"]</label>
                </td>
                <td style="width:40%">                   
                    <label id="lblArticleRef" style="color:green;"></label>
                </td>
                <td style="width:8%">
                   <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="Close()">Close</a>
                </td>
            </tr>       
        </table>        
    </fieldset>
</div>
</body>
</html>

<script type="text/javascript">
    var _oKnitDyeingProgramAttachments=[]
    $(document).ready(function () {

        _oKnitDyeingProgramAttachments=@Html.Raw(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Model.KnitDyeingProgramAttachments));
        var sOperationInfo =@Html.Raw(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Model.ErrorMessage));
        $("#lblArticleRef" ).html(sOperationInfo);
        RefreshList(_oKnitDyeingProgramAttachments);
 });

 $('#btnDelete').click(function (e) {
    //debugger;
     var oKnitDyeingProgramAttachment= $('#tblKnitDyeingProgramAttachment').datagrid('getSelected');
     if(oKnitDyeingProgramAttachment==null ||  parseInt(oKnitDyeingProgramAttachment.KnitDyeingProgramAttachmentID)<=0)
    {
        alert("Invalid Attachment!!! please select a valid Attachment!");
        return false;
    }
    if (!confirm("Confirm to Delete?")) return ;

    var SelectedRowIndex=$('#tblKnitDyeingProgramAttachment').datagrid('getRowIndex',oKnitDyeingProgramAttachment);

    if (oKnitDyeingProgramAttachment.KnitDyeingProgramAttachmentID > 0)
    {
        $.ajax
        ({
            type: "POST",
            dataType: "json",
            url : sessionStorage.getItem("BaseAddress")+  "/KnitDyeingProgramAttachment/DeleteAttachment",
            data:  JSON.stringify(oKnitDyeingProgramAttachment),
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                //debugger;
                feedbackmessage = jQuery.parseJSON(data);
                if (feedbackmessage == "Data Delete Successfully")
                {
                    alert("Delete sucessfully");
                    $('#tblKnitDyeingProgramAttachment').datagrid('deleteRow',SelectedRowIndex);

                }
                else
                {
                    alert(feedbackmessage);
                }
            },
            error: function (xhr, status, error)
            {
                alert(error);
            }

        });
    }
});

function FormatDownload(value)
{
    debugger;
    var nPOAID =parseInt(value);
    var s = '   <input type="image" src="@Url.Content("~/Content/CSS/icons/down.png")"   onclick="DownLoadAttachment('+nPOAID+')", value="" id="btnDownload"'+nPOAID+'/> ';    
    return s;
    }

    function FormatApproved(value)
    {
        debugger;
        var s='';
        if(value==true)
        {
            s = '   <input type="image" src="@Url.Content("~/Content/CSS/icons/ok.png")"   value=""/> ';
        }
        return s;
    }

    function DownLoadAttachment(nPOAID)
    {
        debugger;
        if(nPOAID==null || nPOAID<=0)
        {
            alert("Please select a item from list!");
            return;
        }
        var oParameter = new Object();
        var tsv= ((new Date()).getTime())/1000;
        var url =_sBaseAddress+  "/KnitDyeingProgramAttachment/DownloadAttachment?id="+ nPOAID+"&ts="+tsv;
        window.open(url, '_blank');
    }

    function RefreshList(oKnitDyeingProgramAttachments)
    {
        data=oKnitDyeingProgramAttachments;
        data={"total":""+data.length+"","rows":data};
        $('#tblKnitDyeingProgramAttachment').datagrid('loadData',data);
    }

    function Close()
    {
        window.close();
    }
</script>